apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRWVc0c3d2aERkaG40R0hLMFA5aHltekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEl3TXpFeE1UY3pObG9YRFRNMU1USXdNVEV4TVRjegpObG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCR1lKa1lQRFFYbFpIcG5pTWRlbnVIckVFaDE2bktJV0JXZ1NCWjlEUW9TWFQwdmxieklpMmlsYlQrMEoKRkx1RXcwNlpVcGxDT2xEWlhRUnRFcFFsSjFlallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVvMzBPc2Q2NW15bkZIbVA2cWlaRW9IRmZ5aUV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUlZV2pOQzYKTlcxYXRReXVWb3plc1RXWE5PL2RyQWpjcXUrcEU1endoUWFCQWlBaUNNcFdLTk9IYXpQUXhwdTRsS1ZxZ05GQQp3WUVpQjZqSlhWSTBsbXZVWkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.200.0.1:6443
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin@mycluster
  name: admin@mycluster
current-context: admin@mycluster
kind: Config
preferences: {}
users:
- name: admin@mycluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVNxZ0F3SUJBZ0lRZUZkZUEreUxkdlBQZS91RTRyWTMxVEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEl3TXpFeU5Ua3hOMW9YRFRJMk1USXdNekV5TlRreQpOMW93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFYzg1aFRCSGNSbTJTUmpxOWd5blNvZHRUUWRteXpoYlQKSkE3dTJ1SnkxRW1TaVRTdnVvKzNubnl6WmdZTlB2VVdOWFNGVHdvZXpLSDRhNktXSXROaG42TklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGS045CkRySGV1WnNweFI1aitxb21SS0J4WDhvaE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lDbzgzQlprQkpPQVZGYXYKYXhQQjhRbUxHbXM1Wm5rSXg3UWdkYjlSNHN4aUFpRUFsUFBqaHpzKzBacDkrR3llQ3FkOXRtZ050cHVZcjlaVwpRSStZRnJwOUVSTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5xOU1KWTlsRzF3OWNqZ2toQ0NWS1dqNm5MY0QvNnNUbzJwbVlITFJZSW5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYzg1aFRCSGNSbTJTUmpxOWd5blNvZHRUUWRteXpoYlRKQTd1MnVKeTFFbVNpVFN2dW8rMwpubnl6WmdZTlB2VVdOWFNGVHdvZXpLSDRhNktXSXROaG53PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
